name: gag_cars_frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  step_progress_indicator: ^1.0.2
  image_picker: ^1.0.4
  provider: ^6.1.2
  path: ^1.8.3

  pin_code_fields: ^8.0.1
  otp_pin_field: ^1.4.1
  pinput: ^6.0.1
  country_code_picker: ^3.3.0
  country_picker: ^2.0.15
  lottie: ^3.3.1
  syncfusion_flutter_sliders: ^31.1.19
  flutter_colorpicker: ^1.1.0
  syncfusion_flutter_datepicker: ^31.1.19
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.1.1
  google_places_flutter: ^2.0.1  
  http: ^1.4.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cloudinary: ^1.2.0
  device_info_plus: ^12.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  flutter_libphonenumber: ^2.5.1
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^5.1.0
  intl: ^0.20.2
  jiffy: ^6.2.1
  flutter_spinkit: ^5.2.1
  uuid: ^4.5.1
  
  url_launcher: ^6.3.2
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.0
  camera: ^0.11.2+1
  google_mlkit_face_detection: ^0.13.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  dio: ^5.4.0
  permission_handler: ^12.0.1
  paystack: ^0.0.2
  package_info_plus: ^9.0.0
  webview_flutter: ^4.4.2
  flutter_feather_icons: ^2.0.0+1
  icons_plus: ^5.0.0

  # NEW PACKAGES FOR RECEIPT FUNCTIONALITY
  pdf: ^3.10.4
  printing: ^5.11.1
  open_file: ^3.3.1
  emoji_picker_flutter: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - .env